descriptionFormat: ''
handle: media
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: Medien
productFieldLayouts:
  670d136e-3ffb-46f1-8c13-20624e91d1a7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 81914777-e47a-42b8-a9e9-685bcced9569
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76e9c4cd-0e3f-4927-bc94-f9c295e2b7a8 # Medienportal Titelbild
            instructions: null
            label: Titelbild
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29273b5c-ff99-4650-a95e-c578259c2ffe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 708709a9-02a0-41c1-8931-0b37fea52893 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5299d693-1c8d-43ca-a92c-88bebbb35499
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 521f96ac-3b44-4e73-a05f-311c6df1f990 # Body
            instructions: null
            label: Beschreibung
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfb79c8b-7750-48de-8795-dd501180fbb5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: b05a0398-0f57-4560-8eb2-680f88383a9a
            userCondition: null
            warning: null
          -
            elementCondition: null
            fieldUid: 0c70ccd0-641c-4388-afd5-99577e98ab14 # Modification date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 563f05d2-09b3-466d-b8ca-5316cb643b60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 43300a32-87a4-4948-9c0a-ddbc95cc09cb
            userCondition: null
          -
            elementCondition: null
            fieldUid: 260a1a7f-ec83-4903-a647-de657eaefbb7 # Nur Download
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1d0001f-e4fa-49d9-86e4-2f9ca5485980
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8286755e-ec43-43e2-8da6-a46d71fbf625 # Medienart
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23c8439b-b6bc-4d2c-85e8-29dcd4288089
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 502865fd-4a00-472b-9d29-70ed249fbebf # Themen Medienportal
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 024a5091-15e6-40bb-8bc8-f130a49a2efe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fb35bb6-913b-4e90-83da-9b4bbaa184d0 # Branchen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 751e2f3a-9a7a-4364-af71-e6fb8812aa51
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 48f1a755-e705-451c-8d9d-77204e066f2f # Zielgruppen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc821944-6c7c-4b8d-a8fe-7e14e5fb3044
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 8ffbf291-032e-4025-bfab-e4de4523e60a
            userCondition: null
          -
            elementCondition: null
            fieldUid: 70705f1c-d8c7-41bd-a27c-037c30582bd3 # Medienkonzept
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bc60f62-9b42-49ca-b6a7-cbcc5f765891
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b49767c2-cfb5-4c5e-a1f5-75901c72182e # Download URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0036aa5-9510-41ee-85c7-e15d26774e32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c5ef96fd-41d8-42db-8864-688be6377664 # Download Filename
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da7fd568-5a1b-4f79-a8c3-320651c0d2b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39d56999-f9ab-4dae-9479-bc2ee2efcb43 # Download Content-Typ
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b0999d4-7e50-4f98-9c12-c0941e17ab75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea9b526a-b66c-4883-8661-cc54c7dbb3bf # Download Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44acc9b5-b7bf-4ff1-b8ca-7c1b35383664
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 212c1f1e-f7c8-4ed3-9d52-5a7d53426bf9
            userCondition: null
          -
            elementCondition: null
            fieldUid: 92b37031-751f-4c8f-95f6-d417b247b2b3 # Artikelreferenzen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa849308-6065-4e6b-9b53-d8a1fd1f6f9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98c7bda6-34df-400e-a887-20d17efd637b # Items (Files)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d794b59e-fc5f-4142-8245-d3365f884904
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d805d34c-50be-4b1b-bd45-d0bc53a2e0f8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2696d3ea-1bef-4106-a7d8-231a6499bef8 # Interne Bemerkungen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b01c91a2-eacc-44b5-9182-bf1d91544af9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e34fc6d-2d74-45dd-a19a-bdeb4f3c9474 # Medienart Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 917306a6-edcb-44b0-8240-64203c22a4ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 200606da-2722-4f6e-99f3-9243e42aa6d0 # URL original
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a7059bb-ae89-4515-b181-cce5b842c864
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53541d99-0c99-427f-8a9e-2057eeff4eb5 # Plone Slug
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 655ebb90-4aaf-4800-b876-0e85a3734b07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6bedf22b-8e52-4b66-8308-5de1ebf11188 # Plone UID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8d76506-5f9f-47af-819d-bb5d7afe9a93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9535d1b7-e342-417e-8b4b-7239c5d508fa # Webcode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 214142c4-b10b-49c5-9e95-5db5aaf7b3c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3917625a-8792-4c1a-87cc-f49ee1ab9ab5
            userCondition: null
          -
            elementCondition: null
            fieldUid: fb0fb474-89f7-4241-a86b-a604b12cc913 # Data Beispiel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e1c96ec-6c90-4267-b38b-4bd3af451729
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 092a070c-522b-4a5a-8d08-c79ce415bdd8
        userCondition: null
productTitleFormat: ''
siteSettings:
  1e22bb49-6a25-47c2-a69b-f91816938557: # Inventar
    hasUrls: true
    template: _artikel.twig
    uriFormat: '../medien/artikel/{slug}'
  265b612b-3848-4489-a762-54ddab4e55af: # BG ETEM Intranet
    hasUrls: false
    template: null
    uriFormat: null
  0920ba4c-ca0e-4187-b14f-53ff8d14c625: # Das Magazin Ihrer Berufsgenossenschaft
    hasUrls: false
    template: null
    uriFormat: null
  a2821711-f9c3-46b0-ae5e-158625c1ee52: # BGHW
    hasUrls: false
    template: null
    uriFormat: null
  be74105c-0631-4876-b742-694f9b7ac20a: # BG ETEM Medienportal
    hasUrls: true
    template: _artikel.twig
    uriFormat: 'artikel/{slug}'
  c267be8c-ada1-4920-8ecf-cc60914aed52: # Keycloak
    hasUrls: false
    template: null
    uriFormat: null
  e0b4acfc-09c1-474a-bd31-ec67021e719d: # bgetem
    hasUrls: false
    template: null
    uriFormat: null
skuFormat: ''
variantTitleFormat: '{product.title}'
