fieldLayouts:
  1668be30-eb8c-4588-8984-a197d933cc79:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7647a5df-136e-4435-aa3e-6ce92543884b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa33e5a3-c7e8-4d64-a83e-7936b142f04c # Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 524526bb-67e5-4e98-b453-890a8a291426
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: b1d274a9-73bf-45d7-a166-4144c05f98d4
        userCondition: null
handle: bgEtemIntranetHomeAlternativ
hasTitleField: true
name: '[BG ETEM Intranet Home] Alternativ'
section: 84723f8c-8158-4198-a2d9-3c31f18dae7d # [BG ETEM Intranet Home] Alternativ
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
