fieldLayouts:
  be5924bf-e422-4eb1-8f3b-3c605bbb44af:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecfbc0e4-d307-4b5e-9743-d70932df0918
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa33e5a3-c7e8-4d64-a83e-7936b142f04c # Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f22c08e0-41f5-42db-a47f-9a6e4af741fb
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 936335ac-8667-4a1c-938d-b77d6683c861
        userCondition: null
handle: bghwSicherUndGesundArbeiten
hasTitleField: true
name: '[BGHW] Sicher und gesund arbeiten'
section: 7645eba5-0351-458d-8478-17ad0725c98b # [BGHW] Sicher und gesund arbeiten
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
