fieldLayouts:
  0e426abe-77a6-4a7f-9571-75978e74825a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 425dfe22-8e00-42b8-9a56-012786e49da0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa33e5a3-c7e8-4d64-a83e-7936b142f04c # Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da06633b-c38c-4458-b953-0e4eaccf8c11
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 4d1a66db-8bff-4ccd-9806-184bc7691e5f
        userCondition: null
handle: bghwOrganisation
hasTitleField: true
name: '[BGHW] Organisation'
section: 74fda7a1-ae3f-4658-a1d3-d8700b578b64 # [BGHW] Organisation
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
