fieldLayouts:
  7c8161b5-c6df-4056-9327-d9a87980683a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: faa6279f-d80a-4311-bda4-d132547a953f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa33e5a3-c7e8-4d64-a83e-7936b142f04c # Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba4ae36c-2030-4c0d-a4be-00536011606f
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: bb1f5419-7ec3-44c6-8f27-627cbd0f5f3f
        userCondition: null
handle: cluster
hasTitleField: false
name: Cluster
section: 1e7b52e7-a6f4-4b0e-bbc1-1069018fcc28 # Cluster
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
