fieldLayouts:
  67d4c6d5-cc62-4d19-ae8c-17735ee44518:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 52274058-3a8f-4aa4-b676-8c8ed1611044
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2e08fc6-148b-41dc-829a-1deb370f2e1f # Cover
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 077bad10-6f0f-4c99-9e10-f1abee63c468
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5240590f-1525-4ad9-ac44-c941d17ad8b9 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1007a9e3-d018-4680-afef-b910bbdd0c0d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d13413a5-6169-4db0-bfa5-91b3a694e00b # Item URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fccc3aeb-4dba-43d0-a75b-84d053f94c3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6bedf22b-8e52-4b66-8308-5de1ebf11188 # Plone UID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb10c771-5f39-43d4-9115-f4a7b160ef93
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: faf297a4-0d82-43ba-b175-83319aee076c
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: f8cc4e9e-68c4-4d4c-9824-fe07f74be890 # Kampagnen
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
