fieldLayouts:
  03a64131-75e7-4f95-a3a0-e0796269c80e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1460b900-cfb5-4e30-9c2e-7e2e447cd216 # Dachzeile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c93db288-2e41-43d5-b9dd-78f2951164f4
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 64653850-15ea-47ca-9a02-3486ddf55ce6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2e08fc6-148b-41dc-829a-1deb370f2e1f # Cover
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3d1db1f-d889-453b-9b80-c69df47bae97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ce0f41d-9c0f-4f1c-9665-adc24d7321e4 # Audiodatei
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db55b4c3-ad2b-4ccb-be1b-bb3e3790915a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 975f42d9-32c1-4ab4-9d92-d462aa237239 # Soundcloud Track ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 275367f7-ba18-4b2e-ba2e-fd7364c7543b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8c6be3f-2d8d-41d5-a62e-bb205a1fa331 # Embded Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f95a539-4daa-4842-ba1f-1e39785d7392
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ac51d1b4-71b5-477d-beb5-c2da2db71708
            userCondition: null
          -
            elementCondition: null
            fieldUid: 708709a9-02a0-41c1-8931-0b37fea52893 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99b7a822-2f10-421c-b6ff-0e17e22e3b93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 521f96ac-3b44-4e73-a05f-311c6df1f990 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db706181-d857-4afa-82e7-59d7da503a56
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 969422a8-e3d7-496f-bfdc-e4a313bc0a31 # Shownotes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: addd4fcb-2c4c-471c-9772-47f4e45a9ca0
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 78c634a7-18ee-4dd4-a1d6-b649689988a7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6bedf22b-8e52-4b66-8308-5de1ebf11188 # Plone UID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49528a04-e876-4395-a902-66b41090360c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9535d1b7-e342-417e-8b4b-7239c5d508fa # Webcode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0085a375-e9ce-4a18-ac3c-2e6572cb45f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d06db2be-ccea-4c08-8b2f-813028ba9c01
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8497e6c1-8aa9-43be-b92c-4eff8408d606 # Cardcolor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cb8590c-c018-4209-9646-dc68a3ed88e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c2dc27d-f280-41f7-b406-84eb7a6f67d2 # Colorcode title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fa38442-f8c9-42e7-99df-59169df6bd01
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ab0089d-d353-43a8-84ef-cabd9f9b5fa0 # Colorcode Hex
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f75ca58-f2d2-4c9a-96dd-5f9e7b19026c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7d530736-1493-4f96-8b2f-0c381eafb0ab
            userCondition: null
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 99520332-cbd3-4b3e-9c72-ee692ea9c78c
            userCondition: null
          -
            elementCondition: null
            fieldUid: a874a5ff-0499-4dfc-b727-4c6fbaca1ba7 # Galerieposition
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf8f19d4-276b-481c-a938-b8cc0205e6e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 16deb46b-a727-48d1-a9f2-17c3fbc4161b # Small
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d66a8912-5ae6-42d5-b133-bf2f651ce6a1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b7bbb443-8e7c-4be3-9690-736faf916c1d # Medium
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2ee6fdd-785f-42c3-aac4-8dc9541bfe51
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6b22a029-9f3c-43da-ab0c-19484758e8b7 # Large
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b565d9e-348e-4fac-b2ee-6e0f6b4874b9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d214e59c-cc95-4d87-98f9-c38caeded93d
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3e37fd6e-521f-42a2-aae4-f63c4733c7b0 # Previous Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f3b7e1e-551f-4c4c-afaf-96c7307eb901
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4e78878f-47aa-47a9-8e34-5d9bb1ebe0c0 # Next Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72704607-6676-4e90-bf2b-b1cc92480562
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9ca9ea9a-3796-48b7-be0c-7474cc2081b5
            userCondition: null
          -
            elementCondition: null
            fieldUid: 181cef0e-45db-489c-af21-e0b8c8efbf0f # Previous Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90814173-de3a-47fa-a55f-d93734b7adad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80fd4a33-4f65-4889-8027-613220c56557 # Previous Item Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5e6389b-7c07-4eff-866e-94f3e8b5abcc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75210d2d-2a19-44d7-ad92-67f63d68048a # Previous Item URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 108eeebb-6128-4794-9742-3e71bfd298c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: afb589d6-5bdb-4c32-bb59-0fb2d9591f7c # Next Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d40b54b2-7213-442e-9c61-51f44eecae97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5308f625-2e37-4886-a374-dabe6876ff09 # Next Item Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4240b7f4-5156-4cd0-819c-9cf2c2d0876b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e338728-c003-49e3-b5db-f6cbc348171f # Next Item URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 252e4aa2-1a02-4c07-9bc5-5cc6a77d4d1e
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: a97a258e-c6c2-4347-bdc4-08d79d75929d
        userCondition: null
handle: podcast
hasTitleField: true
name: Podcast
section: d72b6749-cdcf-4fae-b301-4fb276ea7af9 # Presse-Aktuelles
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
