fieldLayouts:
  a6514f13-b594-4946-ac5a-b342dc8869f4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 43843773-3e2d-4644-be8b-a23b1e7047ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7cae9fd-1be3-4d89-a7fa-090c21d05a43 # Ort
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 848a649d-dc54-4ae9-9a30-8648d314a428
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b22ab796-420a-41bf-afac-42427c322fa2 # Termin Start
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efdf6b7b-52df-40b5-96dd-8890a6cad671
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b4bb988-7ea1-409a-acad-f0c54d78fcc6 # Termin Ende
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f62afc3c-7063-446d-ad4c-3ff7b4f309c7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: abfae7f9-d019-4fa1-a1f3-8e743c97f5c7 # Termin URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa71f6e4-30dd-4b70-b0d1-7e3cc15d9627
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e83231a-8956-4d31-8506-f9e905dee038 # Kontaktperson
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e2d7338-b7f2-4b6a-b449-b52eb8f9715a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a5790d28-8359-4a0e-99b4-3daa6c6a42dc
        userCondition: null
handle: termin
hasTitleField: true
name: Termin
section: 01611f33-6e74-462d-a255-b45020496a92 # Termine
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
