defaultPlacement: end
fieldLayouts:
  885fbb62-5f3a-4690-b28d-112625092479:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: b4c34742-c904-4d97-93bf-92155cc01778
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 708709a9-02a0-41c1-8931-0b37fea52893 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ab963f7-488a-4f56-96f6-f67b9012b412
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 200606da-2722-4f6e-99f3-9243e42aa6d0 # URL original
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 395e9518-5870-454f-b870-9b491871d3c2
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 3e27d260-ebe1-4ce0-b62e-9ffb3e8adb54
        userCondition: null
handle: handlungsebenen
name: Handlungsebenen
siteSettings:
  1e22bb49-6a25-47c2-a69b-f91816938557: # Inventar
    hasUrls: false
    template: null
    uriFormat: null
  187b2b2b-01ad-4963-b201-d3e5050521a8: # BG ETEM
    hasUrls: false
    template: null
    uriFormat: null
  265b612b-3848-4489-a762-54ddab4e55af: # BG ETEM Intranet
    hasUrls: false
    template: null
    uriFormat: null
  0920ba4c-ca0e-4187-b14f-53ff8d14c625: # Das Magazin Ihrer Berufsgenossenschaft
    hasUrls: false
    template: null
    uriFormat: null
  a2821711-f9c3-46b0-ae5e-158625c1ee52: # BGHW
    hasUrls: false
    template: null
    uriFormat: null
  be74105c-0631-4876-b742-694f9b7ac20a: # BG ETEM Medienportal
    hasUrls: false
    template: null
    uriFormat: null
  c267be8c-ada1-4920-8ecf-cc60914aed52: # Keycloak
    hasUrls: false
    template: null
    uriFormat: null
  e0b4acfc-09c1-474a-bd31-ec67021e719d: # bgetem
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 12b08bee-3658-4bae-b2a6-dbd5105405fb
