baseUrl: '@rootUrl/bgetemintranet'
enabled: '1'
handle: bgetemIntranet
hasUrls: true
language: de-DE
name: 'BG ETEM Intranet'
primary: false
siteGroup: 3d14b3e6-9841-4b6f-95a9-77fe717967f5 # bgetem
sortOrder: 6
