childBlocks:
  - textkarte
  - linkkarte
  - listenkarte
  - apikarte
conditions: null
description: null
enabled: true
field: fa33e5a3-c7e8-4d64-a83e-7936b142f04c # Module
fieldLayouts:
  b3792131-ea04-48cd-a306-4c8cf5afb61d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 81f0465c-b748-4122-8893-9e53b76c37c7 # Überschrift
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a370b95-25fd-493c-855e-52d994f4e5a2
            userCondition: null
            warning: null
            width: 100
        name: Karten
        uid: 359680f2-66b7-411f-a952-0210d82294f7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 875b5abb-fd1b-48a9-8d59-afaa93058564 # Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41cc59b5-8573-4367-90a1-b16163bbd747
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: 3bc5f64e-a89e-4297-afad-b7e3f1062e37
        userCondition: null
group: null
groupChildBlockTypes: true
handle: cluster
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Cluster
sortOrder: 1
topLevel: true
