childBlocks: null
conditions: null
description: null
enabled: true
field: fa33e5a3-c7e8-4d64-a83e-7936b142f04c # Module
fieldLayouts:
  486495ae-5ba9-4e41-b446-d13f9ff4f9d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f9f6fbdf-4b31-4008-a500-e75ac60f6f54 # Linkfeld
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc08b150-092e-4d8e-95cd-0e3b1ec7f586
            userCondition: null
            warning: null
            width: 100
        name: Inhalte
        uid: dd40929e-278b-4fbf-8921-cb894dc3cdda
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d2e08fc6-148b-41dc-829a-1deb370f2e1f # Cover
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0c40135-558f-4dbc-83a4-766181148fac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1460b900-cfb5-4e30-9c2e-7e2e447cd216 # Dachzeile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3204a23d-ba38-4b38-bc37-c0a53b4293a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 81f0465c-b748-4122-8893-9e53b76c37c7 # Überschrift
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3d7b47b-b945-482f-b05c-e6cc7931dd4e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 521f96ac-3b44-4e73-a05f-311c6df1f990 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f58f34b0-b297-4cfe-ab3e-aef5305e5c04
            userCondition: null
            warning: null
            width: 100
        name: 'Eigene Inhalte'
        uid: 43c27083-4b09-4f1b-9530-533a7b5233d8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 729e8099-e116-420e-bb48-cff32ac2289d # Kartenbreite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38c6754c-c8af-44f5-9ca8-9725beb9054f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 16333976-8b8b-46fe-b762-21fbfd44c6f7 # Cover Full
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30ccebf9-c0fe-437c-97c7-e3b6069334d0
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 875b5abb-fd1b-48a9-8d59-afaa93058564 # Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ddae402-7c94-4f0a-bf01-d143f31c0e28
            userCondition: null
            warning: null
            width: 25
        name: Einstellungen
        uid: 333a2558-48e9-4cd1-9bf3-8185c0d3f817
        userCondition: null
group: f976ef3d-bbf8-4cc1-8c45-b634eee2c77a # Karten
groupChildBlockTypes: true
handle: linkkarte
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Linkkarte
sortOrder: 8
topLevel: false
