childBlocks: null
conditions: null
description: null
enabled: true
field: fa33e5a3-c7e8-4d64-a83e-7936b142f04c # Module
fieldLayouts:
  e8bcf1dc-a08a-4e1e-b1a6-a06138d5b05c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 875b5abb-fd1b-48a9-8d59-afaa93058564 # Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41175091-2ecb-4b10-b0fc-a22ba998184e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 729e8099-e116-420e-bb48-cff32ac2289d # Kartenbreite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2fc0909-e5f8-43f1-8cf6-28966f6e20bf
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: 6e9f193e-68ea-4d50-9113-0286a4833f67
        userCondition: null
group: null
groupChildBlockTypes: true
handle: sliderProdukte
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Slider Produkte'
sortOrder: 4
topLevel: true
