tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 14cb1faa-28ae-49d6-8bef-0dc0aee46264 # User Ort
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 57a38141-ae26-40a9-b803-5fb9af21cbba
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 1bf79d3a-9242-4f72-a771-9558a8c3685f # Auswahl Standortnews
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: cdf41842-a400-45d5-9f7d-905f81f11282
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: e9e726c0-acd5-4251-b5af-68854db60da9 # Auswahl Bereichsnews
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: cc5826df-66fe-4c4b-bbfb-38dbdeabdb39
        userCondition: null
        warning: null
        width: 100
    name: Custom
    uid: a466aff7-d4f7-4f23-bee0-ab57ba0478ed
    userCondition: null
