fieldLayouts:
  fa74feee-865b-40e5-b4f8-7a6f37bffb75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c479286b-2386-45f9-bb24-ef1826a32298
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 785ffb6b-dfab-4d64-862a-ba9d9a7276a7 # Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95c249e6-4b06-4faa-a517-50c2d5f45c83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 191d740e-8fa8-47c2-9d0e-66ee2727176b # Img Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7dba149f-9023-4000-8dcf-59dc63c0cbe5
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 9714d161-532d-4892-9ac8-16a22f72cd9e
        userCondition: null
fs: bilderBghw
handle: bilderBghw
name: 'Bilder BGHW'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: none
transformFs: ''
transformSubpath: ''
