columnSuffix: wwkmedvg
contentColumnType: boolean
fieldGroup: c866deda-e6cc-48ea-8562-52f0654d5db2 # _Common
handle: arrowed
instructions: null
name: Arrowed
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
