columnSuffix: null
contentColumnType: string
fieldGroup: a4bfdfaa-c7aa-4b43-94e1-6eb1a196866f # Medienportal
handle: artikelreferenzen
instructions: null
name: Artikelreferenzen
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'productType:5f496c4d-7f46-4b46-9a52-525d2847b63c' # Medien
  targetSiteId: be74105c-0631-4876-b742-694f9b7ac20a # BG ETEM Medienportal
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\commerce\fields\Products
