columnSuffix: null
contentColumnType: string
fieldGroup: d3f57e59-0c8a-492b-817e-785c378f3689 # Podcast
handle: audioFile
instructions: null
name: Audiodatei
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - audio
  branchLimit: null
  defaultUploadLocationSource: 'volume:a0676db7-6c36-487e-92a6-d422e742e1cb' # Podcasts
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:a0676db7-6c36-487e-92a6-d422e742e1cb' # Podcasts
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:a0676db7-6c36-487e-92a6-d422e742e1cb' # Podcasts
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
