columnSuffix: null
contentColumnType: string
fieldGroup: a4bfdfaa-c7aa-4b43-94e1-6eb1a196866f # Medienportal
handle: branchen
instructions: null
name: Branchen
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:38d071a0-2ede-478b-a2fc-854dd8ab2889' # Branchen
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
