columnSuffix: mzdwgfxg
contentColumnType: text
fieldGroup: 6c8ca4b5-faaa-4685-9881-dc933c2a9500 # Meta
handle: colorcodeTitle
instructions: null
name: 'Colorcode title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
