columnSuffix: null
contentColumnType: string
fieldGroup: c866deda-e6cc-48ea-8562-52f0654d5db2 # _Common
handle: cover
instructions: null
name: Cover
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:43ce67ae-cfa2-4680-9235-dd9546b9803e' # Bilder Magazin
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:43ce67ae-cfa2-4680-9235-dd9546b9803e' # Bilder Magazin
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
