columnSuffix: null
contentColumnType: string
fieldGroup: f7adbec1-88b8-4b4d-b69e-81a47947015d # Magazin
handle: division
instructions: null
name: Sparte
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:96857f58-b529-435a-8085-18765db64ec9' # Sparte Magazin
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
