columnSuffix: fkbemjur
contentColumnType: integer(10)
fieldGroup: a4bfdfaa-c7aa-4b43-94e1-6eb1a196866f # Medienportal
handle: downloadSize
instructions: null
name: 'Download Size'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
