columnSuffix: null
contentColumnType: string
fieldGroup: c866deda-e6cc-48ea-8562-52f0654d5db2 # _Common
handle: eintraege
instructions: null
name: Einträge
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:7703ab3d-a038-425d-9545-3a0c453b355e' # Anwendungen
    - 'section:666abca7-3afa-46a7-8e2e-3e10dd276a91' # Links und Recherche
    - 'section:d72b6749-cdcf-4fae-b301-4fb276ea7af9' # Presse-Aktuelles
    - 'section:3a4fe6b3-7fa2-47a7-aa8f-3c8a0e2defb0' # Quicklinks
    - 'section:ba022acb-eb7e-409e-a25a-1eab9f9b01c2' # Stellenanzeigen
    - 'section:01611f33-6e74-462d-a255-b45020496a92' # Termine
    - 'section:b292b1ca-4d77-45e7-97a2-da468c18c880' # [BGHW] ABC Tabelle
    - 'section:0408cca5-e827-40c8-9397-89c062429004' # [BGHW] Aktuelle Meldungen
    - 'section:b87426b2-2875-4462-abf0-a1e3a4462caa' # [BGHW] Aufgaben
    - 'section:7104933b-77b4-49f4-a8d1-14f5389901c9' # [BGHW ]Termine
    - 'section:0158b508-0e9f-4d41-9410-4e298cd84b2e' # [Magazin] Artikel
    - 'section:8bb547f6-733a-4d2f-a80b-9e11ade49f9b' # [Magazin] Ausgaben
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
