columnSuffix: wdygauqo
contentColumnType: integer(10)
fieldGroup: c866deda-e6cc-48ea-8562-52f0654d5db2 # _Common
handle: filesize
instructions: null
name: Dateigröße
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
