columnSuffix: qrlsubed
contentColumnType: text
fieldGroup: 98dc625b-051e-4332-adef-2dd98e633dec # Dateien
handle: imgRights
instructions: null
name: Bildrechte
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
