columnSuffix: akopiquj
contentColumnType: text
fieldGroup: f7adbec1-88b8-4b4d-b69e-81a47947015d # Magazin
handle: infobox2
instructions: null
name: Infobox2
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: false
  redactorConfig: null
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
