columnSuffix: null
contentColumnType: string
fieldGroup: a4bfdfaa-c7aa-4b43-94e1-6eb1a196866f # Medienportal
handle: items
instructions: null
name: 'Items (Files)'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:b890a41b-568a-4087-931a-5be48bec6918' # Files
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
