columnSuffix: tjqekpuu
contentColumnType: integer(10)
fieldGroup: 88e1572c-f3c5-4214-a261-b079e6234963 # Ausgaben
handle: jahr
instructions: null
name: Jahr
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
