columnSuffix: ggbawdbu
contentColumnType: string
fieldGroup: cd49009d-49c7-44c2-adce-81651a699347 # BGHW
handle: kartenbreite
instructions: null
name: Kartenbreite
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '1/3 Breite'
        -
          - value
          - 'col-12 col-lg-4'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '2/3 Breite'
        -
          - value
          - 'col-12 col-lg-8'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '1/4 Breite'
        -
          - value
          - 'col-12 col-lg-3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3/4 Breite'
        -
          - value
          - 'col-12 col-lg-9'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '1/2 Breite'
        -
          - value
          - 'col-12 col-lg-6'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'ganze Breite'
        -
          - value
          - col-12
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
