columnSuffix: pmlgxyin
contentColumnType: string
fieldGroup: c866deda-e6cc-48ea-8562-52f0654d5db2 # _Common
handle: linkfield
instructions: null
name: Linkfeld
searchable: false
settings:
  allowCustomText: true
  allowTarget: false
  autoNoReferrer: false
  customTextMaxLength: 0
  customTextRequired: false
  defaultLinkName: entry
  defaultText: ''
  enableAllLinkTypes: false
  enableAriaLabel: false
  enableElementCache: false
  enableTitle: false
  typeSettings:
    asset:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
    category:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
    craftCommerce-product:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: true
      sources: '*'
    custom:
      allowAliases: false
      disableValidation: false
      enabled: true
    email:
      allowAliases: false
      disableValidation: false
      enabled: false
    entry:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: true
      sources: '*'
    site:
      enabled: false
      sites: '*'
    tel:
      allowAliases: false
      disableValidation: false
      enabled: false
    url:
      allowAliases: false
      disableValidation: false
      enabled: false
    user:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: true
      sources: '*'
translationKeyFormat: null
translationMethod: none
type: lenz\linkfield\fields\LinkField
