columnSuffix: nitjmgqh
contentColumnType: integer(10)
fieldGroup: 6c8ca4b5-faaa-4685-9881-dc933c2a9500 # Meta
handle: medium
instructions: null
name: Medium
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
