columnSuffix: null
contentColumnType: string
fieldGroup: c866deda-e6cc-48ea-8562-52f0654d5db2 # _Common
handle: modules
instructions: null
name: Module
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
