columnSuffix: null
contentColumnType: string
fieldGroup: 6c8ca4b5-faaa-4685-9881-dc933c2a9500 # Meta
handle: previousEntry
instructions: null
name: 'Previous Entry'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:0158b508-0e9f-4d41-9410-4e298cd84b2e' # [Magazin] Artikel
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
