columnSuffix: null
contentColumnType: string
fieldGroup: cd49009d-49c7-44c2-adce-81651a699347 # BGHW
handle: schmuckbildBghw
instructions: null
name: '[BGHW] Schmuckbild'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:43ce67ae-cfa2-4680-9235-dd9546b9803e' # Bilder Magazin
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:7c2086e6-43ff-45bb-8cf1-5457f668ee34' # Bilder BGHW
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
