fieldLayouts:
  b57daf6c-9817-43f3-9673-6c2d6f0a1e5e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 229349fa-32d0-458b-a8d3-557561b1f844 # Infobanner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f0075b0-1357-40c7-a7b6-8e31cdfd468f
            userCondition: null
            warning: null
            width: 100
        name: 'Banner Einträge'
        uid: 5b8c6be3-0e4f-440f-ab80-af171052ad99
        userCondition: null
handle: banner
name: Banner
sortOrder: 2
