defaultPlacement: end
enableVersioning: true
handle: abcTabelle
name: '[BGHW] ABC Tabelle'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a2821711-f9c3-46b0-ae5e-158625c1ee52: # BGHW
    enabledByDefault: true
    hasUrls: true
    template: abctabelle/_entry
    uriFormat: 'abc-tabelle/{slug}'
type: channel
