defaultPlacement: end
enableVersioning: true
handle: bghwVertretungenUndBeauftragte
name: '[BGHW] Vertretungen und Beauftragte'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a2821711-f9c3-46b0-ae5e-158625c1ee52: # BGHW
    enabledByDefault: true
    hasUrls: true
    template: landingpage.twig
    uriFormat: vertretungen-und-beauftragte
type: single
