defaultPlacement: end
enableVersioning: true
handle: bghwSicherUndGesundArbeiten
name: '[BGHW] Sicher und gesund arbeiten'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a2821711-f9c3-46b0-ae5e-158625c1ee52: # BGHW
    enabledByDefault: true
    hasUrls: true
    template: landingpage
    uriFormat: sicher-und-gesund-arbeiten
type: single
