defaultPlacement: end
enableVersioning: true
handle: inventar
name: Inventar
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1e22bb49-6a25-47c2-a69b-f91816938557: # Inventar
    enabledByDefault: true
    hasUrls: true
    template: inventar/index.twig
    uriFormat: __home__
type: single
