defaultPlacement: end
enableVersioning: true
handle: magazin
name: '[Magazin] Artikel'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre Eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1e22bb49-6a25-47c2-a69b-f91816938557: # Inventar
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '../magazin/{ausgabe}/{sammlung.value}/{slug}'
  0920ba4c-ca0e-4187-b14f-53ff8d14c625: # Das Magazin Ihrer Berufsgenossenschaft
    enabledByDefault: true
    hasUrls: true
    template: magazin/_entry
    uriFormat: '{ausgabe}/{sammlung.value}/{slug}'
  be74105c-0631-4876-b742-694f9b7ac20a: # BG ETEM Medienportal
    enabledByDefault: true
    hasUrls: true
    template: magazin/_entry
    uriFormat: '../magazin/{ausgabe}/{sammlung.value}/{slug}'
type: channel
