defaultPlacement: end
enableVersioning: true
handle: podcastStartseite
name: 'Podcast Startseite'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  187b2b2b-01ad-4963-b201-d3e5050521a8: # BG ETEM
    enabledByDefault: true
    hasUrls: true
    template: bgetem/index
    uriFormat: __home__
type: single
