defaultPlacement: end
enableVersioning: true
handle: quicklinks
name: Quicklinks
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  265b612b-3848-4489-a762-54ddab4e55af: # BG ETEM Intranet
    enabledByDefault: true
    hasUrls: true
    template: quicklinks/_entry
    uriFormat: 'quicklinks/{slug}'
type: channel
